config/routes.rb
Rails.application.routes.draw do

  resources :exhibitions
  resources :reviews
  resources :artworks

  root 'home#home'

  get 'addartwork', to: 'home#webform'
  get 'contact', to: 'home#contact'

  post 'request_contact', to: 'home#request_contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
# one-to-many relationship : one artwork can have many reviews and many exhibitions
  has_many :reviews, dependent: :destroy
  has_many :exhibitions, dependent: :destroy
  validates_presence_of :name, :artist, :year, :description
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
# an exhibition can belong to only one artwork
  belongs_to :artwork
  validates :venue, :artwork, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
# a review can belong to only one artwork
  belongs_to :artwork
  validates :review, :artwork, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: %i[ show edit update destroy ]

  # GET /artworks or /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1 or /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks or /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: "Artwork was successfully created." }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1 or /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: "Artwork was successfully updated." }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1 or /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: "Artwork was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artwork_params
      params.require(:artwork).permit(:name, :artist, :year, :description)
    end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: %i[ show edit update destroy ]
  before_action :set_artwork, only:[:new, :create]

  # GET /exhibitions or /exhibitions.json
  def index
    @exhibitions = Exhibition.all
  end

  # GET /exhibitions/1 or /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = @artwork.exhibitions.new
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions or /exhibitions.json
  def create
    @exhibition = @artwork.exhibitions.new(exhibition_params)

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: "Exhibition was successfully created." }
        format.json { render :show, status: :created, location: @exhibition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1 or /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: "Exhibition was successfully updated." }
        format.json { render :show, status: :ok, location: @exhibition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1 or /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url, notice: "Exhibition was successfully destroyed." }
      format.js { flash[:notice] = "Exhibition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    def set_artwork
      @artwork = Artwork.find_by(id: params[:artwork_id]) || Artwork.find(exhibition_params[:artwork_id])
    end

    # Only allow a list of trusted parameters through.
    def exhibition_params
      params.require(:exhibition).permit(:artwork_id, :venue)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def webform
    @artwork = Artwork.new
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end

    redirect_to root_path
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :set_artwork, only:[:new, :create]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = @artwork.reviews.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = @artwork.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.js { flash[:notice] = "Review was successfully destroyed."}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_artwork
      @artwork = Artwork.find_by(id: params[:artwork_id]) || Artwork.find(review_params[:artwork_id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:artwork_id, :review)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/artworks/_form.html.haml
= form_for @artwork, :html => {:id => "ArtworkForm"} do |form|
  - if @artwork.errors.any?
    #error_explanation
      %h2
        = pluralize(@artwork.errors.count, "error")
        prohibited this artwork from being saved:
      %ul
        - @artwork.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :artist
    = form.text_field :artist
  .field
    = form.label :year
    = form.number_field :year
  .field
    = form.label :description
    = form.text_field :description
  .actions
    = form.submit

app/views/artworks/edit.html.haml
%h1 Editing Artwork
= render 'form', artwork: @artwork
= link_to 'Show', @artwork
|
\#{link_to 'Back', artworks_path}

app/views/artworks/index.html.haml
%h1 Artworks

%table
  %thead
    %tr
      %th Name
      %th Artist
      %th Year
      %th Description
      %th
      %th
      %th

  %tbody
    - @artworks.each_with_index do |artwork, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"

      %tr
        %td{:class => "#{row_class}"}= artwork.name
        %td{:class => "#{row_class}"}= artwork.artist
        %td{:class => "#{row_class}"}= artwork.year
        %td{:class => "#{row_class}"}= artwork.description
        %td{:class => "#{row_class}"}= link_to t('.show'), artwork
        %td{:class => "#{row_class}"}= link_to t('.edit'), edit_artwork_path(artwork)
        %td{:class => "#{row_class}"}= link_to t('.destroy'), artwork, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/artworks/new.html.haml
%h1 New Artwork

= render 'form'

= link_to 'Back', artworks_path

app/views/artworks/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @artwork.name
%p
  %strong Artist:
  = @artwork.artist
%p
  %strong Year:
  = @artwork.year
%p
  %strong Description:
  = @artwork.description

%p Reviews:
%table
  %tbody
    - @artwork.reviews.each_with_index do |review, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"

      %tr{id: "review_#{review.id}"}
        %td{:class => "#{row_class}"}= review.review
        %td{:class => "#{row_class}"}= link_to t('.show'), review
        %td{:class => "#{row_class}"}= link_to t('.edit'), edit_review_path(review)
        %td{:class => "#{row_class}"}= link_to t('.destroy'), review, :method => :delete, :data => { :confirm => 'Are you sure?'}, :remote => true

%p= link_to 'Add Review', new_review_path(artwork_id: @artwork)

%p Exhibitions:
%table
  %tbody
    - @artwork.exhibitions.each_with_index do |exhibition, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"

      %tr{id: "exhibition_#{exhibition.id}"}
        %td{:class => "#{row_class}"}= exhibition.venue
        %td{:class => "#{row_class}"}= link_to 'Show', exhibition
        %td{:class => "#{row_class}"}= link_to 'Edit', edit_exhibition_path(exhibition)
        %td{:class => "#{row_class}"}= link_to 'Destroy', exhibition, :method => :delete, :data => { :confirm => 'Are you sure?'}, :remote => true

%p= link_to 'Add Exhibition', new_exhibition_path(artwork_id: @artwork)

= link_to 'Edit', edit_artwork_path(@artwork)
|
\#{link_to 'Back', artworks_path}

app/views/exhibitions/_form.html.haml
= form_for @exhibition, :html => {:id => "ExhibitionForm"} do |f|
  - if @exhibition.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exhibition.errors.count, "error")} prohibited this exhibition from being saved:"
      %ul
        - @exhibition.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :artwork
    %p= @exhibition.artwork.name
    =f.hidden_field :artwork_id, value: @exhibition.artwork.id
  .field
    = f.label :venue
    = f.text_field :venue
  .actions
    = f.submit 'Save'

app/views/exhibitions/destroy.js.erb
$('#exhibition_<%= @exhibition.id%>').hide();

app/views/exhibitions/edit.html.haml
%h1 Editing exhibition

= render 'form'

= link_to 'Show', @exhibition
\|
= link_to 'Back', exhibitions_path

app/views/exhibitions/index.html.haml
%h1 Exhibitions

%table
  %thead
    %tr
      %th Artwork
      %th Venue
      %th
      %th
      %th

  %tbody
    - @exhibitions.each_with_index do |exhibition, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"

      %tr
        %td{:class => "#{row_class}"}= exhibition.artwork.name
        %td{:class => "#{row_class}"}= exhibition.venue
        %td{:class => "#{row_class}"}= link_to t('.show'), exhibition
        %td{:class => "#{row_class}"}= link_to t('.edit'), edit_exhibition_path(exhibition)
        %td{:class => "#{row_class}"}= link_to t('.destroy'), exhibition, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/exhibitions/new.html.haml
%h1 New exhibition

= render 'form'

= link_to 'Back', exhibitions_path

app/views/exhibitions/show.html.haml
%p#notice= notice

%p
  %b Artwork:
  = @exhibition.artwork.name
%p
  %b Venue:
  = @exhibition.venue

= link_to t('.edit'), edit_exhibition_path(@exhibition)
\|
= link_to t('.back'), exhibitions_path

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')

-# contact form
= form_tag request_contact_path, method: 'post' do
  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size: 50

  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')

  = label_tag :telephone, t('.telephone')
  = telephone_field_tag :telephone, '', title: t('.enter_telephone')

  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100
  %b &nbsp
  = submit_tag t('.submit')

app/views/home/home.html.haml
%h1= t('.title')
%p= t('.welcome')

-# adding an image for the home page
=image_tag "home_illustration.jpg", :class => "my_image"

app/views/home/webform.html.haml
-# a form for adding new artworks for our collection

%h1 New Artwork

= render 'artworks/form'

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

    = favicon_link_tag asset_path('favicon.png')

    - if content_for?(:head)
      = yield(:head)

    - if content_for?(:foot)
      = yield(:foot)

  %body

    - flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?
    =render('shared/header')
    =render('shared/footer')
    = yield

app/views/reviews/_form.html.haml
= form_for @review, :html => {:id => "ReviewsForm"} do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :artwork
    %p= @review.artwork.name
    =f.hidden_field :artwork_id, value: @review.artwork.id
  .field
    = f.label :review
    = f.text_field :review
  .actions
    = f.submit 'Save'

app/views/reviews/destroy.js.erb
$('#review_<%= @review.id %>').hide();

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Reviews

%table
  %thead
    %tr
      %th Artwork
      %th Review
      %th
      %th
      %th

  %tbody
    - @reviews.each_with_index do |review, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"

      %tr
        %td{:class => "#{row_class}"}= review.artwork.name
        %td{:class => "#{row_class}"}= review.review
        %td{:class => "#{row_class}"}= link_to t('.show'), review
        %td{:class => "#{row_class}"}= link_to t('.edit'), edit_review_path(review)
        %td{:class => "#{row_class}"}= link_to t('.destroy'), review, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Artwork:
  = @review.artwork.name
%p
  %b Review:
  = @review.review

= link_to t('.edit'), edit_review_path(@review)
\|
= link_to t('.back'), reviews_path

app/views/shared/_footer.html.haml
-# add css for the footer partial in separate file
- content_for :foot do
  %link{:href => "/assets/footer.scss", :rel => "stylesheets"}/

%footer
  Author: Elena Atanasova

app/views/shared/_header.html.haml
-# add css for the header partial in separate file
- content_for :head do
  %link{:href => "/assets/navheader.scss", :rel => "stylesheets"}/

-# navigation bar
%ul
  %li
    %a{:href => "/"} Home
  %li
    %a{:href => "artworks"} Artworks
  %li
    %a{:href => "exhibitions"} Exhibitions
  %li
    %a{:href => "reviews"} Reviews
  %li
    %a{:href => "addartwork"} New Artwork
  %li
    %a{:href => "contact"} Contact Us